#include <bits/stdc++.h>
using namespace std;

void solve(long long H, long long A) {
  long long res = 0;
  while (0 < H) {
    H -= A;
    res++;
  }
  cout << res << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  long long H;
  scanf("%lld", &H);
  long long A;
  scanf("%lld", &A);
  solve(H, A);
  return 0;
}
